### ISSUE TITLE
JCommander.newBuilder().addObject(analysis).build().parse(args) not working in GenerateSingleAirPollutionValue.java

### ISSUE THREAD

**Issue by jingjunL** [matsim-vsp/matsim-ruhrgebiet#4]
I know this is a code from a very long time ago, but I am currently seeking a code example that can analyse the emission event files and produce XML files similar to the output in public SVN of MATSim Berlin scenario V5.4 (link: https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-1pct/output-berlin-v5.4-1pct/). So I found this java class.

This may be because of the MATSim version. I tried to copy the code from `GenerateSingleAirPollutionValue` (here: https://github.com/matsim-scenarios/matsim-ruhrgebiet/blob/1.1.x/src/main/java/org/matsim/ruhrgebiet/analysis/GenerateSingleAirPollutionValue.java) and, weirdly, the below code cannot be compiled:

`JCommander.newBuilder().addObject(analysis).build().parse(args);`

Specifically, it cannot solve the method `newBuilder` in `JCommander`.

I am using MATSim version `15.0-PR2490`, but this project is based on version `12`. I checked my `pom` and noticed that I don't have the dependency of `jcommander`, so I copied below code to my pom:

```
        <dependency>
            <groupId>com.beust</groupId>
            <artifactId>jcommander</artifactId>
            <version>1.71</version>
        </dependency>
```

Unfortunately, this is what I get, saying maven cannot find this version
<img width="267" alt="1682610560875" src="https://user-images.githubusercontent.com/63421908/234916810-bff8fb61-128d-4669-9403-f09aeeee22c5.png">

So can you maybe give me some hints about how to fix this? Or, if you have a more recent script for analysing the emission event files?

Thanks :)

**Comment by Janekdererste** [comment]
Hi @jingjunL , we have an [example here](https://github.com/matsim-org/matsim-code-examples/blob/15.x/src/main/java/org/matsim/codeexamples/extensions/emissions/RunAverageEmissionToolOfflineExample.java) and then there are example in the [emission contrib](https://github.com/matsim-org/matsim-libs/tree/master/contribs/emissions/src/main/java/org/matsim/contrib/emissions/example) itself. Usually, those example should be up to date. 

If you really want to make the script from that specific repository work, you probably have to switch to another [JCommander version](https://mvnrepository.com/artifact/com.beust/jcommander) e.g. 1.82.

**Comment by jingjunL** [comment]
> Hi @jingjunL , we have an [example here](https://github.com/matsim-org/matsim-code-examples/blob/15.x/src/main/java/org/matsim/codeexamples/extensions/emissions/RunAverageEmissionToolOfflineExample.java) and then there are example in the [emission contrib](https://github.com/matsim-org/matsim-libs/tree/master/contribs/emissions/src/main/java/org/matsim/contrib/emissions/example) itself. Usually, those example should be up to date.
> 
> If you really want to make the script from that specific repository work, you probably have to switch to another [JCommander version](https://mvnrepository.com/artifact/com.beust/jcommander) e.g. 1.82.

Hi @Janekdererste , I know there are examples in the code example to run emission contrib but that's not my problem. We have had our Brussels scenario run with emission contrib, but the output is just a very long `event` file which needs to be processed with `eventHander` (for instance, I would like to calculate the total emission within my study area). As I know, in the Berlin scenario, there are some outputs like `berlin-v5.4-1pct.emissions.CO2_TOTAL.csv`, so before I go in deep to write my own script, I would first like to find some examples as I think there must be someone who has done this (that's why I find here https://github.com/matsim-scenarios/matsim-ruhrgebiet/blob/1.1.x/src/main/java/org/matsim/ruhrgebiet/analysis/GenerateSingleAirPollutionValue.java). Do you maybe have some latest script for emission analysis? Thanks :)

**Comment by Janekdererste** [comment]
Ah, in this case. This script will still do its job. You can of course move the code to your repository and replace JCommander with which ever command line parsing you like.

**Comment by jingjunL** [comment]
Solved now. Thanks @Janekdererste :)
